refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console

  info:
    kind: rolling_file
    path: "log/info.log"
    encoder:
      pattern: "{d} - {m}{n}"
    
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: delete

  errors:
    kind: file
    path: "log/errors.log"
    encoder:
      pattern: "{d} - {m}{n}"

  
  zephyr:
    kind: file
    path: "log/zephyr_programs.log"
    encoder:
      pattern: "{d} - {m}{n}"

  backend:
    kind: file
    path: "log/backend.log"
    encoder:
      pattern: "{d} - {m}{n}"

root:
  level: warn
  appenders:
    - stdout
    - errors

loggers:
  info:
    level: info
    appenders:
      - info
    additive: false
  
  zephyr:
    level: info
    appenders:
      - zephyr
    additive: false

  backend:
    level: info
    appenders:
      - backend
    additive: false
