[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.7"
tokio = {workspace=true}
anyhow = {workspace=true}
serde = {workspace=true}
reqwest = {workspace=true}
serde_json = {workspace=true}
stellar-xdr = {workspace=true}
tokio-tungstenite = "0.16"
futures = "0.3"
tungstenite = "0.17"
url = "2"
sha2 = {workspace=true}
bincode = {workspace=true}
stellar-strkey = {workspace=true}
toml = "0.8.9"
base64 = "0.22.1"
async-trait = "0.1.86"
